//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quyettien.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.CashBillDetails = new HashSet<CashBillDetail>();
            this.InstallmentBillDetails = new HashSet<InstallmentBillDetail>();
        }
    
        public int ID { get; set; }
        public string ProductCode { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập tên sản phẩm")]
        [MinLength(5, ErrorMessage = "Tên sản phẩm không được ít hơn 5 kí tự")]
        [MaxLength(100, ErrorMessage = "Tên sản phẩm không được vượt quá 100 kí tự")]
        public string ProductName { get; set; }
        public int ProductTypeID { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập giá bán")]
        [Range(0, 2000000000, ErrorMessage = "Giá bán trong khoảng từ 0 đến 2.000.000.000")]
        public int SalePrice { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập giá gốc")]
        [Range(0, 2000000000, ErrorMessage = "Giá gốc trong khoảng từ 0 đến 2.000.000.000")]
        public int OriginPrice { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập giá góp")]
        [Range(0, 2000000000, ErrorMessage = "Giá góp trong khoảng từ 0 đến 2.000.000.000")]
        public int InstallmentPrice { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập số lượng")]
        [Range(0, 100000, ErrorMessage = "Số lượng trong khoảng từ 0 đến 100000")]
        public int Quantity { get; set; }

        public string Avatar { get; set; }
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashBillDetail> CashBillDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstallmentBillDetail> InstallmentBillDetails { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
